# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-10-24T00:41:23+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class User(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None


class Recipe(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    mins_prep: Optional[int] = None
    category_id: Optional[int] = None
    mins_cook: Optional[int] = None
    description: Optional[str] = None
    author_id: Optional[int] = None
    default_servings: Optional[int] = None


class RecipeList(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    description: Optional[str] = None


class Review(BaseModel):
    id: Optional[int] = None
    stars: Optional[int] = None
    author_id: Optional[int] = None
    content: Optional[str] = None
    recipe_id: Optional[int] = None


class Ingredient(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    ingredient_category_id: Optional[int] = None
    storage_location_id: Optional[int] = None
